import Head from 'next/head'
import Image from 'next/image'
import { motion } from 'framer-motion';


// Components
import Header from '@/components/Header'
import Hero from '@/components/Hero'
import About from '@/components/About'
import Experience from '@/components/Experience'
import Project from '@/components/Project'
import Skills from '@/components/Skills'
import Contact from '@/components/Contact'
import { GetStaticProps } from 'next';
import { WorkExperience, PageInfo, Projects, Technology, Social } from '@/typings';
import {fetchPageInfo} from '../utils/fetchPageInfo'
import { fetchExperience } from '@/utils/fetchExperience';
import { fetchProject } from '@/utils/fetchProject';
import { fetchSkills } from '@/utils/fetchSkills';
import { fetchSocials } from '@/utils/fetchSocials';


type Props = {
  pageInfo: PageInfo,
  experience: WorkExperience[],
  skill: Technology[],
  projects: Projects[],
  socials: Social[],
}


export default function Home({
  pageInfo,
  experience,
  projects,
  skill,
  socials,
}: Props) {
  return (
    <div className='bg-[rgb(36,36,36)] h-screen text-white snap-y snap-mandatory overflow-y-scroll overflow-x-hidden scrollbar-thin scrollbar-track-gray-900 scrollbar-thumb-[#f7ab0a]/50 z-0'>
      <Head>
        <title>Sarthak&apos;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
      </Head>
      <main >
          <Header socials={socials} />

          {/* //hero */}
          <section id="hero" className='snap-center scroll-smooth'>
          <Hero pageInfo={pageInfo}/>
          </section>

          {/* about */}
          <section id="about" className='snap-center scroll-smooth' >
          <About pageInfo={pageInfo} />
          </section>


          {/* experience */}
          { experience.length !== 0 && 
            <section id="experience" className='snap-center scroll-smooth'>
            <Experience experience={experience} />
          </section>}

          {/* skills */}
          <section id="skills" className='snap-center scroll-smooth'>
            <Skills skills={skill} />
          </section>

          {/* projects */}
          <section id="project"className='snap-center scroll-smooth'>
            <Project projects={projects} />
          </section>

          {/* contact */}
          <section id="contact" className='snap-center scroll-smooth'>
            <Contact pageInfo={pageInfo} />
          </section>


      </main>
    </div >
  )
}



export const getStaticProps: GetStaticProps<Props> = async () => {
  const pageInfo: PageInfo = await fetchPageInfo()
  const experience: WorkExperience[] = await fetchExperience()
  const skill : Technology[]  = await fetchSkills()
  const projects: Projects[] = await fetchProject()
  const socials: Social[] = await fetchSocials()

  return {
    props: {
      pageInfo,
      experience,
      skill,
      projects,
      socials,
    },
    revalidate: 100
  }


}