import Head from 'next/head'
import Image from 'next/image'
import { motion } from 'framer-motion';


// Components
import Header from '@/components/Header'
import Hero from '@/components/Hero'
import About from '@/components/About'
import Experience from '@/components/Experience'
import Project from '@/components/Project'
import Skills from '@/components/Skills'
import Contact from '@/components/Contact'







export default function Home() {
  return (
    <div className='bg-[rgb(36,36,36)] h-screen text-white snap-y snap-mandatory overflow-y-scroll overflow-x-hidden scrollbar-thin scrollbar-track-gray-600 scrollbar-thumb-[#f7ab0a]/50 z-0'>
      <Head>
        <title>Sarthak Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
          <Header />

          {/* //hero */}
          <section id="hero" className='snap-center scroll-smooth'>
          <Hero />
          </section>

          {/* about */}
          <section id="about" className='snap-center scroll-smooth' >
          <About />
          </section>


          {/* experience */}
          <section id="experience" className='snap-center scroll-smooth'>
            <Experience />
          </section>

          {/* skills */}
          <section id="skills" className='snap-center scroll-smooth'>
            <Skills />
          </section>

          {/* projects */}
          <section id="project"className='snap-center scroll-smooth'>
            <Project />
          </section>




          {/* contact */}
          <section id="contact" className='snap-center scroll-smooth'>
            <Contact />
          </section>


      </main>
    </div >
  )
}



